# CC = $(HOME)/emsdk/upstream/bin/clang --target=wasm32
CC = clang --target=wasm32
DEBUG ?= 0

LIBC = $(HOME)/dev/wasmlite/libc

WASM_SOURCEMAP = $(HOME)/dev/tools/emscripten/tools/wasm-sourcemap.py
# NOTE: system llvm-dwarfdump might be too outdated for wasm-sourcemap.py, so we use emsdk repo
DWARFDUMP = $(HOME)/emsdk/upstream/bin/llvm-dwarfdump
# DWARFDUMP = /usr/bin/llvm-dwarfdump

# RENDER_GL ?= 1

SRC = $(wildcard src/*.c src/lib/*.c src/lib/rsa/*.c src/ui/*.c src/custom/*.c)
OBJ = $(SRC:.c=.o)
# remove -fwrapv when code is converted to use unsigned ints or overflow checks are added
CFLAGS += -fwrapv -std=c99 -DWITH_RSA_JS -DWASM --sysroot=$(LIBC)
LDFLAGS += --sysroot=$(LIBC) -nodefaultlibs -lc -Wl,--export-table -Wl,--stack-first -Wl,-z,stack-size=$(shell echo $$((8 << 20)))
# -Wl,--export=malloc

ifeq ($(RENDER_GL), 1)
SRC += $(wildcard src/gl/*.c src/gl/textures/*.c)
CFLAGS += -I ./cglm/include -DRENDER_GL
else
CFLAGS += -DRENDER_SW
endif

ifeq ($(DEBUG), 1)
CFLAGS += -Wall -Wextra -pedantic -g
else
CFLAGS += -Oz -ffast-math -flto
endif

mudclient.wasm: $(OBJ)
	$(CC) -o $@ $^ $(LDFLAGS)
ifeq ($(DEBUG),0)
	wasm-opt $@ -o $@ -Oz
	wasm-strip $@
else
	$(WASM_SOURCEMAP) $@ -w $@ -p $(CURDIR) -s -u ./$@.map -o $@.map --dwarfdump=$(DWARFDUMP)
endif

clean:
	rm -f src/*.o src/lib/*.o src/lib/rsa/*.o src/ui/*.o
	rm -f src/gl/*.o src/gl/textures/*.o src/custom/*.o
	rm -f mudclient mudclient.*

